default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  host: localhost 
  database: movies_api_dev
  # username: <%= ENV['POSTGRES_USER'] || ''%>
  # password: <%= ENV['POSTGRES_PASSWORD'] || '' %>

test:
  <<: *default
  database: movies_api_test %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>